trigger:
  - main

pr:
  - main

variables:
  - name: isBranchMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: build_and_test
    displayName: "Build and test"
    jobs:
      - template: ./pipeline/jobs/set-build-version-job.yml
      - template: ./pipeline/jobs/build-job.yml
      - template: ./pipeline/jobs/unit-tests-job.yml

  - stage: deploy_dev
    displayName: "Deploy to dev"
    dependsOn: build_and_test
    condition: and(succeeded(), eq(variables.isBranchMain, true))
    variables:
      - group: TOOLKIT-COMMON-DEV
      - group: TOOLKIT-BOILERPLATE-DEV
    jobs:
      - template: ./pipeline/jobs/deploy-job.yml
        parameters:
          deployment_token: $(deployment.static_app_token)
          environment: "dev"

  - stage: deploy_preprod
    displayName: "Deploy to preprod"
    dependsOn: build_and_test
    condition: and(succeeded(), eq(variables.isBranchMain, true))
    variables:
      - group: TOOLKIT-COMMON-PREPROD
      - group: TOOLKIT-BOILERPLATE-PREPROD
    jobs:
      - template: ./pipeline/jobs/deploy-job.yml
        parameters:
          deployment_token: $(deployment.static_app_token)
          environment: "preprod"

  - stage: deploy_prod
    displayName: "Deploy to prod"
    dependsOn: build_and_test
    condition: and(succeeded(), eq(variables.isBranchMain, true))
    variables:
      - group: TOOLKIT-COMMON-PROD
      - group: TOOLKIT-BOILERPLATE-PROD
    jobs:
      - template: ./pipeline/jobs/deploy-job.yml
        parameters:
          deployment_token: $(deployment.static_app_token)
          environment: "prod"